### PR TITLE
Resolve remotefindingservice, if sound is completely loaded.

### PR DESCRIPTION
**Pull request by konstantinkrassmann**
See https://github.com/danielstern/ngAudio/issues/136

### CODE REVIEW

**Comment by danielstern** [comment]
@konstantinkrassmann Looks good, I'm worried that removing `loadstart` would break compatibility on other versions. Could you update the PR so that both are included?

**Comment by konstantinkrassmann** [comment]
I just realized, that this will lead to break applications, which use the ngAudio to play buffered sounds. 

This change will make the service wait until the complete sound is loaded. 

Maybe change the event to _canPlay_ which indicates, that there is already some playable data loaded.

**Comment by danielstern** [comment]
Maybe we can implement both features, allowing the user to set a `bool` on the main ngAudio object, with the default being the current behaviour?
Something like, `ngAudio.fireEventOnLoadCompleteOnly`

**Comment by konstantinkrassmann** [comment]
yeah, this sounds good.

**Comment by konstantinkrassmann** [comment]
Closing, because of the breaking potential.

**Pull request closed without merging**
