### PR TITLE
Added destroyed getter

### PR DESCRIPTION
**Pull request by simonemazzoni**
Hello,
here is the PR related to #176

Added destroyed getter on NgAudioObject to check if an object has been destroyed or not.

Let me know if it looks ok.

Simone

### CODE REVIEW

**Comment by danielstern** [comment]
Looks good! Just one more thing, can you update the [docs](https://github.com/danielstern/ngAudio/blob/master/app/partial/ngAudioDocs.html) explaining the new feature?

**Comment by simonemazzoni** [comment]
@danielstern, right now I don't have my laptop with me. I'll do it as soon as I can.

**Comment by simonemazzoni** [comment]
@danielstern sorry for the late. 
I updated the docs. Could you please merge it?
Thanks.

**Comment by danielstern** [comment]
Thanks!

**Comment by simonemazzoni** [comment]
@danielstern Great!
Will you please also update npm package?

**Pull request merged**
