### PR TITLE
Added toFinish callback when there are x seconds to end

### PR DESCRIPTION
**Pull request by BreixoAM**

### CODE REVIEW

**Comment by danielstern** [comment]
This looks like an awesome feature, but I'm concerned the event won't fire on mobile. How has this been tested?

**Comment by BreixoAM** [comment]
The code was tested basically adding something like:

$scope.audio.toFinish(10, function() {alert('10 second to finish')});

Is tested on:
Mac with Chrome, Firefox and Safari updated.
And Chrome on Android 6.0, Android 4.3 and Android 4.4

**Comment by danielstern** [comment]
@BreixoAM OK, this code is good. Could you also please update the docs accordingly and we'll get it merged

**Comment by BreixoAM** [comment]
Sure. Update version on package.json and README file right?

**Comment by danielstern** [comment]
@BreixoAM As well as the official docs,
http://danielstern.github.io/ngAudio/#/

Which are located in the gh-pages branch of this repo

**Comment by danielstern** [comment]
Anyone want to finish this off by updating the docs?

**Comment by BreixoAM** [comment]
Sorry for the delay, I just forget it. lol
Not sure if it is all ok now.

**Comment by danielstern** [comment]
I'm going to go ahead and merge this and if anyone finds a problem let me know to undo

**Pull request merged**
