### PR TITLE
Fixes unhandled promise in ng-audio.

### PR DESCRIPTION
**Pull request by mzaman07**
Hello Maintainers,

I am making a PR request to resolve the following [issue](https://github.com/oppia/oppia/issues/5784) being raised in the oppia repo.

I would like to receive feedback on the changes and help with testing on some browsers. Currently I have tested on Firefox 65, Chrome 72.0.3626.96, and Opera 58.0.3135.53.

### Additional Resources
[Autoplay updates](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes)

Thanks,
mzaman07

### CODE REVIEW

**Comment by danielstern** [comment]
Looks pretty great to me! Someone let me know if this breaks anything downstream.

**Comment by andzejsw** [comment]
Actually this version for me is breaking dev build. There is infinite loop for Current Time + Audio not playing. It sometimes plays only while destroy button is clicked. Because of that i am not able to create fork for dependency updates. (Tested on Chrome: Version 73.0.3683.103)

**Comment by danielstern** [comment]
@andzejsw Thats a shame, we've reverted to the previous version.

**Comment by mzaman07** [comment]
I can take a look at this. I'll need to know what steps to see this bug happen and reproduce it.

**Pull request merged**
